export const sidebarMenuItems = [
  {
    _id: "dashboard",
    title: "Dashboard",
    slug: "dashboard",
    category: "api-monitoring",
    href: "/dashboard/",
    order: 1,
  },
  {
    _id: "apis",
    title: "All APIs",
    slug: "apis",
    category: "api-monitoring",
    href: "/dashboard/apis",
    order: 2,
  },
  {
    _id: "incidents",
    title: "Incidents",
    slug: "incidents",
    category: "api-monitoring",
    href: "/dashboard/incidents",
    order: 3,
  },
  {
    _id: "categories",
    title: "Categories",
    slug: "categories",
    category: "api-monitoring",
    href: "/dashboard/categories",
    order: 4,
  },
  {
    _id: "checks",
    title: "Checks",
    slug: "checks",
    category: "api-monitoring",
    href: "/dashboard/checks",
    order: 5,
  },
  {
    _id: "api-leaderboard",
    title: "Leaderboard",
    slug: "leaderboard",
    category: "api-monitoring",
    href: "/dashboard/apis/leaderboard",
    order: 6,
  },

  {
    _id: "cron-monitor",
    title: "Cron Monitor",
    slug: "cron-monitor",
    category: "cron-jobs",
    href: "/dashboard/cron-monitor",
    order: 1,
  },
  {
    _id: "cron-inventory",
    title: "Cron Inventory",
    slug: "cron-inventory",
    category: "cron-jobs",
    href: "/cron-inventory",
    order: 2,
  },
  {
    _id: "cron-job-history",
    title: "Job History",
    slug: "job-history",
    category: "cron-jobs",
    href: "/cron-job",
    order: 3,
  },

  {
    _id: "tenant-global-dashboard",
    title: "Global Dashboard",
    slug: "tenants",
    category: "tenant-monitoring",
    href: "/dashboard/tenant",
    order: 1,
  },
  {
    _id: "tenants",
    title: "Tenants",
    slug: "tenants",
    category: "tenant-monitoring",
    href: "/dashboard/tenants",
    order: 2,
  },
  {
    _id: "endpoint-explorer",
    title: "Endpoint Explorer",
    slug: "endpoint-explorer",
    category: "tenant-monitoring",
    href: "/dashboard/endpoint-explorer",
    order: 3,
  },
  {
    _id: "request-log",
    title: "Request Log",
    slug: "request-log",
    category: "tenant-monitoring",
    href: "/dashboard/request-log",
    order: 4,
  },
  {
    _id: "latency",
    title: "Latency",
    slug: "latency",
    category: "tenant-monitoring",
    href: "/dashboard/latency",
    order: 5,
  },

  {
    _id: "log-explorer",
    title: "Log Explorer",
    slug: "logs",
    category: "logs",
    href: "/log-explorer",
    order: 1,
  },
  {
    _id: "pipeline-monitor",
    title: "Pipeline Monitor",
    slug: "pipeline-monitor",
    category: "logs",
    href: "/pipeline-monitor",
    order: 4,
  },
  {
    _id: "retention-rules",
    title: "Retention Rules",
    slug: "retention-rules",
    category: "logs",
    href: "/retention-rules",
    order: 5,
  },
  {
    _id: "storage-tiers",
    title: "Storage Tiers",
    slug: "storage-tiers",
    category: "logs",
    href: "/storage-tiers",
    order: 6,
  },

  {
    _id: "alerts",
    title: "Alerts",
    slug: "alerts",
    category: "alerts",
    href: "/alerts",
    order: 1,
  },
  {
    _id: "active-alerts",
    title: "Active Alerts",
    slug: "alerts",
    category: "alerts",
    href: "/active-alerts",
    order: 2,
  },
  {
    _id: "alert-rules",
    title: "Alert Rules",
    slug: "alerts",
    category: "alerts",
    href: "/alert-rules",
    order: 3,
  },
  {
    _id: "notification-channels",
    title: "Notification Channels",
    slug: "email-service",
    category: "alerts",
    href: "/notification-channels",
    order: 4,
  },
  {
    _id: "quota-limits",
    title: "Quota Limits",
    slug: "quota-limits",
    category: "alerts",
    href: "/Quota-limits",
    order: 5,
  },

  {
    _id: "saturation",
    title: "Saturation",
    slug: "analytics",
    category: "analytics",
    href: "/saturation",
    order: 1,
  },
  {
    _id: "traffic",
    title: "Traffic",
    slug: "analytics",
    category: "analytics",
    href: "/traffic",
    order: 2,
  },
  {
    _id: "errors",
    title: "Errors",
    slug: "analytics",
    category: "analytics",
    href: "/errors",
    order: 3,
  },
  {
    _id: "slo-dashboard",
    title: "SLO Dashboard",
    slug: "analytics",
    category: "analytics",
    href: "/slo-dashboard",
    order: 4,
  },
  {
    _id: "user-activity",
    title: "User Activity",
    slug: "analytics",
    category: "analytics",
    href: "/user-activity",
    order: 5,
  },
];
